apiVersion: v1
kind: Service
metadata:
  name: ai-recommendation-service
  namespace: savvy
spec:
  selector:
    app: ai-recommendation-service
  ports:
  - port: 8005
    targetPort: 8005
    name: http
  type: ClusterIP
