apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: savvy
spec:
  selector:
    app: finance-service
  ports:
  - port: 8002
    targetPort: 8002
    name: http
  type: ClusterIP
