apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: savvy
spec:
  selector:
    app: notification-service
  ports:
  - port: 8006
    targetPort: 8006
    name: http
  type: ClusterIP
